services:
  frontend:
    build: ./front-end
    container_name: frontend_app
    ports:
      - '3000:3000'
    volumes:
      - ./front-end:/app
      # - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
