services:
  # frontend:
  #   build: ./frontend
  #   container_name: frontend_app
  #   ports:
  #     - '${FRONTEND_PORT:-3000}:3000'
  #   volumes:
  #     - ./frontend:/app:cached
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NODE_ENV=development
  #     - WATCHPACK_POLLING=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - REACT_APP_API_URL=http://backend:8000
  #     - REACT_APP_THEME=${REACT_APP_THEME:-light}
  #     - REACT_APP_DEFAULT_LANGUAGE=${REACT_APP_DEFAULT_LANGUAGE:-pt-BR}
  #     - REACT_APP_ENABLE_ANALYTICS=${REACT_APP_ENABLE_ANALYTICS:-false}
  #     - REACT_APP_ENABLE_CHAT_HISTORY=${REACT_APP_ENABLE_CHAT_HISTORY:-true}
  #     - REACT_APP_MAX_DOCS_UPLOAD=${REACT_APP_MAX_DOCS_UPLOAD:-10}
  #     - REACT_APP_CACHE_DURATION=${REACT_APP_CACHE_DURATION:-30}
  #     - REACT_APP_VERSION=${APP_VERSION:-1.0.0}
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=vector-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
      # - postgres

volumes:
  pgdata:
  node_modules:
  pgadmin_data:
  prometheus_data:
  grafana_data: