global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "rag-metrics"
    static_configs:
      - targets: ["backend:8000"] # Ajuste a porta conforme sua configuração
    metrics_path: "/metrics"
